name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure NPM 7
        run: npm install --global npm@7
      - name: Install packages
        run: npm install
      - name: Lint packages
        run: npm run lint
      - name: Lint scss stylesheets
        run: npm run lint:scss
      - name: Lint css stylesheets
        run: npm run lint:css
      - name: Lint markdown
        run: npm run lint:md
      - name: Lint markdown with remark
        run: npm run lint:rmd
      - name: Lint format
        run: npm run lint:format
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure NPM 7
        run: npm install --global npm@7
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test:skip-cache
      - name: Upload coverage result to codacy
        run: |
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) \
          -- -r coverage/**/*coverage.xml
      - name: Upload coverage result to codecov
        run: |
          bash <(curl -s https://codecov.io/bash) \
          -s coverage/* -t ${{ secrets.CODECOV_TOKEN }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure NPM 7
        run: npm install --global npm@7
      - name: Install packages
        run: npm install
      - name: Build production
        run: npm run build
