name: Release
on:
  push:
    branches:
      - ng10
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Check if @aegis-auth/jwt is already deployed
        run: |
          VERSION=$(cat ".github/version.txt")
          echo "::set-env name=VERSION::$VERSION"
          JWT_IS_ON_NPM=$(if [ ! -z "$(npm view @aegis-auth/jwt@$VERSION 2> /dev/null)" ]; then echo 'true'; else echo 'false'; fi)
          echo "::set-env name=JWT_IS_ON_NPM::$JWT_IS_ON_NPM"
          echo "$VERSION"
          echo "$JWT_IS_ON_NPM"
      - name: Install dependencies
        if: env.JWT_IS_ON_NPM != 'true' && steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        if: env.JWT_IS_ON_NPM != 'true'
        run: |
          yarn build
          yarn hoist:core
      - name: Build Typedocs
        if: env.JWT_IS_ON_NPM != 'true'
        run: yarn typedoc
      - name: Release @aegis-auth/jwt on NPM
        if: env.JWT_IS_ON_NPM != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish ./dist/libs/jwt --access public --tag ng10
