name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Version
        id: cache-version
        uses: actions/cache@v2
        with:
          path: .github/version.txt
          key: version-${{ hashFiles('.github/version.txt') }}
      - name: Setup Node.js
        if: steps.cache-version.outputs.cache-hit != 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        if: steps.cache-version.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build Library
        if: steps.cache-version.outputs.cache-hit != 'true'
        run: yarn build:prod
      - name: Release jwt
        if: steps.cache-version.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish ./dist/libs/jwt --access public
